### ISSUE TITLE
Wrist position in camera space, and relative positions between left and right wrists

### ISSUE THREAD

**Issue by fylwen** [ChanglongJiangGit/A2J-Transformer#10]
Hello. Thanks for sharing the paper and code.

I'm wondering how you model the estimation of wrist position in camera space, and relative positions between left and right wrists in either camera space or right-hand root-aligned space. 

I've read the paper and code, and I feel like that respectively for left and right hands, only the root-aligned joint positions regarding the wrist of the same hand (i.e., left-hand joints referring to the left wrist, right-hand joints referring to the right wrist) are taken into consideration.

Thank you for your time and help!

Best regards,
Frances

**Comment by ChanglongJiangGit** [comment]
Thanks for your attention!

Yes. In our model, we only focus on the root-aligned joint positions regarding the wrist of the same hand as you said. This is because of the lack of 3D information from a single RGB image, the estimation of wrist position in camera space and the  relative positions between left and right wrists is difficult and our network is not well designed for estimating the absolute wrist position in camera space. So we just remove this part.

Hope my answer can solve your problem!

**Comment by fylwen** [comment]
Hello, thank you for the illustration. I will also close the issue then.
